on: push

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            try {
              new Promise(function(resolve, reject) {
                throw new Error("Whoops!");
              })
            } catch (error) {
              console.log(error)
              if (error instanceof Error) core.setFailed(error.message)
            }
